server {
    listen 8081;
    listen [::]:8081;
    
    server_name localhost site1.local;
    
    root /home/danish-ali/DevOps/Nginx/nginx-as-WebServer/websites/site-1;
    index index.html;
    
    location / {
        try_files $uri $uri/ =404;
    }
    

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
    

    access_log /var/log/nginx/site1-access.log;
    error_log /var/log/nginx/site1-error.log;
}
